import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Search, Stethoscope } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import MainLayout from '../layouts/MainLayout';
import { getDoctor, getDoctors } from '../services/doctorService';
import { getSpecialties } from '../services/specialtyService';

export default function DoctorDirectoryPage({ detail = false }) {
  const { t } = useTranslation();
  const { id } = useParams();
  const [doctors, setDoctors] = useState([]); const [doctor, setDoctor] = useState(null); const [specialties, setSpecialties] = useState([]); const [search, setSearch] = useState(''); const [specialty, setSpecialty] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (detail) { getDoctor(id).then((response) => setDoctor(response.data.data)).catch(() => setError(t('doctorDetails'))).finally(() => setLoading(false)); } else { Promise.all([getDoctors({ search, specialty }), getSpecialties()]).then(([doctorResponse, specialtyResponse]) => { setDoctors(doctorResponse.data.data || []); setSpecialties(specialtyResponse.data.data || []); }).catch(() => setError(t('unableToLoadDoctors'))).finally(() => setLoading(false)); } }, [id, detail, search, specialty]);
  if (detail) return <MainLayout><div className="mx-auto max-w-4xl px-6 py-12">{loading ? <p>{t('loadingDoctor')}</p> : error ? <p className="text-rose-600">{error}</p> : <article className="rounded-2xl border border-slate-200 bg-white p-8"><Stethoscope className="text-teal-700" /><h1 className="mt-4 text-3xl font-bold">{doctor?.name}</h1><p className="mt-1 text-teal-700">{doctor?.specialty}</p><p className="mt-6 text-slate-600">{doctor?.bio || t('professionalCare')}</p><Link className="mt-6 inline-flex rounded-xl bg-teal-700 px-4 py-3 text-white" to="/patient/book-appointment">{t('bookAppointment')}</Link></article>}</div></MainLayout>;
  return <MainLayout><div className="mx-auto max-w-6xl space-y-6 px-6 py-12"><div><h1 className="text-3xl font-bold text-slate-900">{t('findADoctor')}</h1><p className="mt-1 text-slate-500">{t('browseClinicalTeam')}</p></div><div className="flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input className="field pl-9" placeholder={t('searchByName')} value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="field max-w-xs" value={specialty} onChange={(event) => setSpecialty(event.target.value)}><option value="">{t('allSpecialties')}</option>{specialties.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div>{error && <p className="text-rose-600">{error}</p>}{loading ? <p>{t('loadingDoctors')}</p> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{doctors.map((item) => <article className="rounded-2xl border border-slate-200 bg-white p-6" key={item.id}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><Stethoscope size={21} /></div><h2 className="mt-4 font-semibold text-slate-900">{item.name}</h2><p className="text-sm text-teal-700">{item.specialty}</p><p className="mt-3 line-clamp-3 text-sm text-slate-500">{item.bio || t('medicareClinician')}</p><Link className="mt-5 inline-block text-sm font-semibold text-teal-700" to={`/doctors/${item.id}`}>{t('viewProfile')}</Link></article>)}{!doctors.length && <p className="text-slate-500">{t('noDoctorsFound')}</p>}</div>}</div></MainLayout>;
}
