import React, { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import AdminLayout from '../../layouts/AdminLayout';
import RoleGuard from '../../components/guards/RoleGuard';
import { createSpecialty, deleteSpecialty, getSpecialties, updateSpecialty } from '../../services/specialtyService';

export default function AdminSpecialtiesPage() {
  const { t } = useTranslation(); const [items, setItems] = useState([]); const [form, setForm] = useState({ name: '', description: '' }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = () => { setLoading(true); getSpecialties().then((response) => setItems(response.data.data || [])).catch((requestError) => setError(requestError.response?.data?.message || t('unableToLoadSpecialties'))).finally(() => setLoading(false)); }; useEffect(load, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { if (editing) await updateSpecialty(editing.id, form); else await createSpecialty(form); setMessage(t(editing ? 'specialtyUpdated' : 'specialtyCreated')); setEditing(null); setForm({ name: '', description: '' }); load(); } catch (requestError) { setError(requestError.response?.data?.message || Object.values(requestError.response?.data?.errors || {}).flat()[0] || t('unableToSaveSpecialty')); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm(t('deleteSpecialtyConfirm', { name: item.name }))) return; try { await deleteSpecialty(item.id); setMessage(t('specialtyDeleted')); load(); } catch (requestError) { setError(requestError.response?.data?.message || t('unableToDeleteSpecialty')); } };
  return <RoleGuard roles={['admin']}><AdminLayout><div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold text-slate-900">{t('specialties')}</h1><p className="mt-1 text-slate-500">{t('keepDirectoryOrganized')}</p></div><button onClick={() => { setEditing(null); setForm({ name: '', description: '' }); }} className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-white"><Plus size={17} />{t('newSpecialty')}</button></div>{message && <p className="text-sm text-emerald-700">{message}</p>}{error && <p className="text-sm text-rose-600">{error}</p>}<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{loading ? <p className="p-8 text-center text-slate-500">{t('loadingSpecialties')}</p> : !items.length ? <p className="p-8 text-center text-slate-500">{t('noSpecialtiesFound')}</p> : <div className="overflow-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{['specialty', 'description', 'specialtyDoctors', 'actions'].map((key) => <th className="p-4" key={key}>{t(key)}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="border-t border-slate-100" key={item.id}><td className="p-4 font-semibold">{item.name}</td><td className="p-4 text-slate-600">{item.description || '—'}</td><td className="p-4">{item.doctors_count ?? 0}</td><td className="flex gap-3 p-4"><button title={t('edit')} className="text-teal-700" onClick={() => { setEditing(item); setForm({ name: item.name, description: item.description || '' }); }}><Pencil size={17} /></button><button title={t('delete')} className="text-rose-700" onClick={() => remove(item)}><Trash2 size={17} /></button></td></tr>)}</tbody></table></div>}</section><form onSubmit={submit} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{t(editing ? 'editSpecialty' : 'createSpecialty')}</h2><input className="field" placeholder={t('specialtyName')} required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><textarea className="field" placeholder={t('description')} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><button disabled={saving} className="w-full rounded-xl bg-teal-700 py-3 font-semibold text-white disabled:opacity-50">{saving ? t('saving') : t(editing ? 'saveChanges' : 'createSpecialty')}</button></form></div></div></AdminLayout></RoleGuard>;
}
